name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Deploy to EC2
        env:
          EC2_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SSH_HOST }}
          EC2_USER: ${{ secrets.SSH_USER }}
          APP_DIR: /home/ubuntu/backend-Parcial1
          APP_FILE: app.py
       
        run: |
          echo "$EC2_PRIVATE_KEY" > ec2_key && chmod 600 ec2_key
          ssh -o StrictHostKeyChecking=no -i ec2_key ${EC2_USER}@${SERVER_IP} '
              # Cambiar al directorio del proyecto
              cd ${APP_DIR} &&
              # Verificar si es un repositorio Git
              git status &&
              # Actualizar el código desde GitHub
              git fetch --all &&
              git reset --hard origin/main &&
              git pull origin main &&
              # Activar el entorno virtual
              source venv/bin/activate &&
              # Instalar dependencias
              pip install -r requirements.txt &&
              # Detener cualquier proceso en el puerto 5000
              sudo fuser -k 5000/tcp &&
              # Ejecutar la aplicación con Gunicorn
              gunicorn -b 0.0.0.0:5000 ${APP_FILE}:app --daemon
          '


